### ISSUE TITLE
Difference between Delta_Pose, Var_Delta_Pose and delta_poses, var_delta_poses

### ISSUE THREAD

**Issue by AgileRoboticsLab** [clfreeman7/IROS2022#1]
[+gaitdef>Gait.m] Is there is specific difference between these variables? It seems that capital ones are w.r.t. the first frame/state (global), while the small letter ones are w.r.t. the tail frame (local). Can the comments be updated if that is correct or correction made?

**Comment by clfreeman7** [comment]
Delta_Pose and delta_poses are both average differences in the SE(2) pose [x, y, theta]' with respect to the instantaneous body frame. However, Delta_pose is the average change in the SE(2) pose over an entire gait cycle (i.e., it is a vector of length 3) while  delta_poses are the average changes in the  SE(2) poses for each motion primitive (i.e., it is a matrix 3xn where n is the number of motion primitives in each gait cycle). 
Similarly, Var_Delta_Pose is the variance in the change in pose over an entire gait cycle while var_delta_poses are the variances in the change in poses for each motion primitive. 

I'll adjust the comments in the class to make this more clear. 
thanks!
